-- 01_create_database.sql  创建数据库 + 完整恢复模式
USE master;
GO
IF DB_ID('DormDB') IS NOT NULL
BEGIN
    ALTER DATABASE DormDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DormDB;
END
GO
CREATE DATABASE DormDB;
GO
ALTER DATABASE DormDB SET RECOVERY FULL;   -- PITR 的前提
GO
